"use strict";

(function initDarts() {
    const canvas = document.getElementById("dartsCanvas");
    if (!canvas) return;
    const context = canvas.getContext("2d");
    const order = [20, 1, 18, 4, 13, 6, 10, 15, 2, 17, 3, 19, 7, 16, 8, 11, 14, 9, 12, 5];
    const center = 300, boardRadius = 280, step = Math.PI * 2 / 20, storageKey = "cuginiparty_darts_records_v1";
    let mode = "practice", difficulty = "easy", remaining = 0, turnStart = 0, turnScore = 0, dartsThisTurn = 0, round = 1, totalScore = 0, impacts = [], gameFinished = false, turnFinished = false, aimPhase = "horizontal", lockedX = null, cursorX = center, cursorY = center, animationFrame = 0, records = readRecords();
    const cursorSpeeds = { easy: { horizontal: .0027, vertical: .0031 }, normal: { horizontal: .0042, vertical: .0048 }, hard: { horizontal: .006, vertical: .0068 } };
    const status = document.getElementById("dartsStatus");

    function readRecords() { try { return { highScore: 0, bestThrow: 0, ...JSON.parse(localStorage.getItem(storageKey) || "{}") }; } catch { return { highScore: 0, bestThrow: 0 }; } }
    function saveRecords() { localStorage.setItem(storageKey, JSON.stringify(records)); }
    function point(angle, radius) { return { x: center + Math.sin(angle) * radius, y: center - Math.cos(angle) * radius }; }
    function pathSegment(start, end, inner, outer) { const outerStart = point(start, outer), innerEnd = point(end, inner); context.beginPath(); context.moveTo(outerStart.x, outerStart.y); context.arc(center, center, outer, start - Math.PI / 2, end - Math.PI / 2); context.lineTo(innerEnd.x, innerEnd.y); context.arc(center, center, inner, end - Math.PI / 2, start - Math.PI / 2, true); context.closePath(); }
    function drawBand(inner, outer, colors) { for (let sector = 0; sector < 20; sector += 1) { const angle = sector * step; pathSegment(angle - step / 2, angle + step / 2, inner, outer); context.fillStyle = colors[sector % 2]; context.fill(); context.strokeStyle = "#d7c9a0"; context.lineWidth = 1; context.stroke(); } }
    function drawDart(impact) { context.save(); context.translate(impact.x, impact.y); context.rotate(impact.angle); context.strokeStyle = "#e9edf1"; context.lineWidth = 4; context.lineCap = "round"; context.beginPath(); context.moveTo(-23, 0); context.lineTo(-2, 0); context.stroke(); context.fillStyle = "#61b7ee"; context.beginPath(); context.moveTo(-31, 0); context.lineTo(-22, -7); context.lineTo(-22, 7); context.closePath(); context.fill(); context.fillStyle = "#f5cc52"; context.beginPath(); context.moveTo(0, 0); context.lineTo(-5, -3); context.lineTo(-5, 3); context.closePath(); context.fill(); context.restore(); }
    function drawCursor() { if (gameFinished || turnFinished) return; context.save(); context.lineWidth = 4; context.shadowBlur = 12; context.shadowColor = "#ffda65"; if (aimPhase === "horizontal") { context.strokeStyle = "#ffda65"; context.beginPath(); context.moveTo(cursorX, 15); context.lineTo(cursorX, 585); context.stroke(); context.fillStyle = "#ffda65"; context.font = "bold 15px system-ui"; context.textAlign = "center"; context.fillText("FERMA X", cursorX, 28); } else if (aimPhase === "vertical") { context.strokeStyle = "rgba(255,218,101,.62)"; context.beginPath(); context.moveTo(lockedX, 15); context.lineTo(lockedX, 585); context.stroke(); context.strokeStyle = "#7ee7ff"; context.shadowColor = "#7ee7ff"; context.beginPath(); context.moveTo(15, cursorY); context.lineTo(585, cursorY); context.stroke(); context.fillStyle = "#7ee7ff"; context.font = "bold 15px system-ui"; context.textAlign = "left"; context.fillText("FERMA Y", 24, Math.max(25, cursorY - 10)); } context.restore(); }
    function drawBoard() { context.clearRect(0, 0, 600, 600); context.fillStyle = "#242323"; context.fillRect(0, 0, 600, 600); drawBand(41, 132, ["#e8d9b4", "#242424"]); drawBand(132, 151, ["#2a9b69", "#c84343"]); drawBand(151, 224, ["#e8d9b4", "#242424"]); drawBand(224, 246, ["#2a9b69", "#c84343"]); context.beginPath(); context.arc(center, center, 41, 0, Math.PI * 2); context.fillStyle = "#2a9b69"; context.fill(); context.beginPath(); context.arc(center, center, 21, 0, Math.PI * 2); context.fillStyle = "#c84343"; context.fill(); context.fillStyle = "#f4ead2"; context.font = "bold 19px system-ui"; context.textAlign = "center"; context.textBaseline = "middle"; order.forEach((value, sector) => { const label = point(sector * step, 264); context.fillText(String(value), label.x, label.y); }); impacts.forEach(drawDart); drawCursor(); }
    function scoreAt(x, y) { const dx = x - center, dy = y - center, radius = Math.hypot(dx, dy) / boardRadius; if (radius > .879) return { score: 0, label: "Fuori", double: false }; if (radius <= .067) return { score: 50, label: "Bull", double: true }; if (radius <= .146) return { score: 25, label: "Bull esterno", double: false }; const angle = Math.atan2(dx, -dy), sector = Math.floor((angle + step / 2 + Math.PI * 2) % (Math.PI * 2) / step), value = order[sector]; if (radius >= .8 && radius <= .879) return { score: value * 2, label: `D${value}`, double: true }; if (radius >= .47 && radius <= .54) return { score: value * 3, label: `T${value}`, double: false }; return { score: value, label: String(value), double: false }; }
    function updateHud() { const primaryLabel = document.getElementById("dartsPrimaryLabel"), primary = document.getElementById("dartsPrimary"), roundLabel = document.getElementById("dartsRoundLabel"); if (mode === "301" || mode === "501") { primaryLabel.textContent = "RIMANENTE"; primary.textContent = remaining; roundLabel.textContent = "TURNO"; document.getElementById("dartsRound").textContent = `${round} · ${dartsThisTurn} / 3`; } else if (mode === "highscore") { primaryLabel.textContent = "TOTALE"; primary.textContent = totalScore; roundLabel.textContent = "ROUND"; document.getElementById("dartsRound").textContent = `${round} / 10 · ${dartsThisTurn} / 3`; } else { primaryLabel.textContent = "PUNTEGGIO"; primary.textContent = totalScore; roundLabel.textContent = "DARDI"; document.getElementById("dartsRound").textContent = `${dartsThisTurn} / 3`; } document.getElementById("dartsTurnScore").textContent = turnScore; const list = document.getElementById("dartsLastThrows"); list.innerHTML = ""; impacts.forEach(impact => { const item = document.createElement("span"); item.className = "darts-throw" + (impact.result.score ? "" : " miss"); item.textContent = `${impact.result.label} · ${impact.result.score}`; list.appendChild(item); }); }
    function startAim(text) { aimPhase = "horizontal"; lockedX = null; status.textContent = text || "Clicca per fermare il cursore orizzontale."; }
    function startGame() { remaining = mode === "301" ? 301 : mode === "501" ? 501 : 0; turnStart = remaining; turnScore = 0; dartsThisTurn = 0; round = 1; totalScore = 0; impacts = []; gameFinished = false; turnFinished = false; startAim(mode === "highscore" ? "10 round da tre freccette: ferma il cursore orizzontale." : mode === "practice" ? "Ferma il cursore orizzontale per scegliere la prima coordinata." : `Chiudi ${remaining} con un doppio: ferma il cursore orizzontale.`); updateHud(); drawBoard(); }
    function beginTurn() { turnStart = remaining; turnScore = 0; dartsThisTurn = 0; impacts = []; turnFinished = false; startAim("Nuovo turno: ferma il cursore orizzontale."); updateHud(); }
    function completeTurn() { turnFinished = true; if (mode === "highscore") { if (round === 10) { gameFinished = true; if (totalScore > records.highScore) { records.highScore = totalScore; saveRecords(); status.textContent = `Partita conclusa: ${totalScore} punti, nuovo record!`; } else status.textContent = `Partita conclusa: ${totalScore} punti. Record: ${records.highScore}.`; } else { round += 1; status.textContent = `Round ${round - 1} concluso. Clicca il tabellone per il prossimo.`; } } else if (mode === "301" || mode === "501") { round += 1; status.textContent = "Turno concluso. Clicca il tabellone per il prossimo."; } else status.textContent = "Serie conclusa. Clicca il tabellone per una nuova serie."; updateHud(); }
    function applyThrow(impact) { const result = impact.result; impacts.push(impact); dartsThisTurn += 1; turnScore += result.score; records.bestThrow = Math.max(records.bestThrow, result.score); saveRecords(); if (mode === "practice" || mode === "highscore") { totalScore += result.score; status.textContent = `${result.label}: ${result.score} punti.`; if (dartsThisTurn === 3) completeTurn(); } else { const next = remaining - result.score; if (next < 0 || next === 1 || (next === 0 && !result.double)) { remaining = turnStart; turnScore = 0; dartsThisTurn = 3; completeTurn(); status.textContent = "BUST! Il punteggio torna all'inizio del turno. Clicca per ripartire."; } else if (next === 0) { remaining = 0; gameFinished = true; status.textContent = `Hai chiuso con ${result.label}: vittoria!`; } else { remaining = next; status.textContent = `${result.label}: ${result.score} punti. Mancano ${remaining}.`; if (dartsThisTurn === 3) completeTurn(); } } if (!gameFinished && !turnFinished) startAim("Clicca per fermare il cursore orizzontale."); updateHud(); drawBoard(); }
    function handleBoardClick() { if (gameFinished) return; if (turnFinished || dartsThisTurn >= 3) { beginTurn(); return; } if (aimPhase === "horizontal") { lockedX = cursorX; aimPhase = "vertical"; status.textContent = "Coordinata orizzontale fissata. Ora clicca per fermare il cursore verticale."; return; } if (aimPhase === "vertical") { const impactX = lockedX, impactY = cursorY; aimPhase = "paused"; applyThrow({ x: impactX, y: impactY, angle: Math.atan2(impactY - center, impactX - center), result: scoreAt(impactX, impactY) }); } }
    function animationLoop(timestamp) { if (!gameFinished && !turnFinished) { const speed = cursorSpeeds[difficulty]; if (aimPhase === "horizontal") cursorX = center + Math.sin(timestamp * speed.horizontal) * 266; if (aimPhase === "vertical") cursorY = center + Math.sin(timestamp * speed.vertical + .9) * 266; drawBoard(); } animationFrame = requestAnimationFrame(animationLoop); }
    canvas.addEventListener("click", handleBoardClick); canvas.addEventListener("keydown", event => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); handleBoardClick(); } }); document.querySelectorAll("[data-darts-mode]").forEach(button => button.addEventListener("click", () => { mode = button.dataset.dartsMode; document.querySelectorAll("[data-darts-mode]").forEach(item => item.classList.toggle("active", item === button)); startGame(); })); document.querySelectorAll("[data-darts-difficulty]").forEach(button => button.addEventListener("click", () => { difficulty = button.dataset.dartsDifficulty; document.querySelectorAll("[data-darts-difficulty]").forEach(item => item.classList.toggle("active", item === button)); startGame(); })); document.getElementById("dartsNewGame").addEventListener("click", startGame); window.addEventListener("pagehide", () => cancelAnimationFrame(animationFrame), { once: true }); startGame(); animationFrame = requestAnimationFrame(animationLoop);
})();
