"use strict";
(function initNumberMerge() {
    const boardElement = document.getElementById("mergeBoard"); if (!boardElement) return;
    const size = 4; const bestKey = "cuginiparty_number_merge_best_v1"; let board = Array(size * size).fill(0); let score = 0; let best = Number(localStorage.getItem(bestKey)) || 0; let reached2048 = false; let gameOver = false; let touchStart = null;
    const statusElement = document.getElementById("mergeStatus"); const modal = document.getElementById("mergeModal"); const modalTitle = document.getElementById("mergeModalTitle"); const modalText = document.getElementById("mergeModalText");
    function index(row, column) { return row * size + column; } function randomEmptyIndex() { const free = board.map((value, cell) => value === 0 ? cell : -1).filter(cell => cell >= 0); return free.length ? free[Math.floor(Math.random() * free.length)] : -1; } function addTile() { const cell = randomEmptyIndex(); if (cell >= 0) board[cell] = Math.random() < .9 ? 2 : 4; }
    function render() { boardElement.innerHTML = ""; board.forEach(value => { const cell = document.createElement("div"); cell.className = "merge-cell"; if (value) { const tile = document.createElement("div"); tile.className = "merge-tile"; tile.dataset.value = String(value); tile.textContent = value; cell.appendChild(tile); } boardElement.appendChild(cell); }); document.getElementById("mergeScore").textContent = score; document.getElementById("mergeBest").textContent = best; }
    function mergeLine(line) { const values = line.filter(Boolean); const result = []; for (let position = 0; position < values.length; position += 1) { if (values[position] === values[position + 1]) { const merged = values[position] * 2; result.push(merged); score += merged; position += 1; } else result.push(values[position]); } return result.concat(Array(size - result.length).fill(0)); }
    function coordinatesFor(direction, line, slot) { if (direction === "left") return [line, slot]; if (direction === "right") return [line, size - 1 - slot]; if (direction === "up") return [slot, line]; return [size - 1 - slot, line]; }
    function canMove() { if (board.includes(0)) return true; return board.some((value, cell) => [cell + 1, cell + size].some(neighbor => neighbor < board.length && ((neighbor === cell + 1 && cell % size !== size - 1) || neighbor === cell + size) && board[neighbor] === value)); }
    function showModal(title, text, value) { document.getElementById("mergeModalValue").textContent = value; modalTitle.textContent = title; modalText.textContent = text; modal.hidden = false; }
    function move(direction) { if (gameOver || !modal.hidden) return; const previous = board.slice(); const beforeScore = score; for (let line = 0; line < size; line += 1) { const values = []; for (let slot = 0; slot < size; slot += 1) { const [row, column] = coordinatesFor(direction, line, slot); values.push(board[index(row, column)]); } const next = mergeLine(values); for (let slot = 0; slot < size; slot += 1) { const [row, column] = coordinatesFor(direction, line, slot); board[index(row, column)] = next[slot]; } } const moved = board.some((value, cell) => value !== previous[cell]); if (!moved) { score = beforeScore; return; } addTile(); if (score > best) { best = score; localStorage.setItem(bestKey, String(best)); } render(); if (!reached2048 && board.some(value => value >= 2048)) { reached2048 = true; showModal("Traguardo raggiunto!", "Hai creato la tessera 2048. Puoi continuare a giocare.", "2048"); } else if (!canMove()) { gameOver = true; statusElement.textContent = "Non ci sono più mosse disponibili."; showModal("Partita finita", `Punteggio finale: ${score}. Riprova a superare il record.`, "✦"); } else statusElement.textContent = "Ottimo: continua a unire le tessere."; }
    function newGame() { board = Array(size * size).fill(0); score = 0; reached2048 = false; gameOver = false; modal.hidden = true; addTile(); addTile(); statusElement.textContent = "Usa frecce, WASD o fai swipe."; render(); }
    document.addEventListener("keydown", event => { const directions = { ArrowLeft: "left", a: "left", A: "left", ArrowRight: "right", d: "right", D: "right", ArrowUp: "up", w: "up", W: "up", ArrowDown: "down", s: "down", S: "down" }; if (directions[event.key]) { event.preventDefault(); move(directions[event.key]); } }); boardElement.addEventListener("touchstart", event => { const touch = event.changedTouches[0]; touchStart = { x: touch.clientX, y: touch.clientY }; }, { passive: true }); boardElement.addEventListener("touchend", event => { if (!touchStart) return; const touch = event.changedTouches[0]; const dx = touch.clientX - touchStart.x; const dy = touch.clientY - touchStart.y; touchStart = null; if (Math.max(Math.abs(dx), Math.abs(dy)) < 22) return; move(Math.abs(dx) > Math.abs(dy) ? (dx > 0 ? "right" : "left") : (dy > 0 ? "down" : "up")); }, { passive: true }); document.getElementById("mergeNewGame").addEventListener("click", newGame); document.getElementById("mergeModalNew").addEventListener("click", newGame); document.getElementById("mergeModalContinue").addEventListener("click", () => { modal.hidden = true; statusElement.textContent = "Continua: il gioco non finisce a 2048."; }); newGame();
})();
