"use strict";

(function initSnake() {
    const canvas = document.getElementById("snakeCanvas");
    if (!canvas) return;
    const context = canvas.getContext("2d");
    const size = 20;
    const storageKey = "cuginiparty_snake_high_score_v1";
    let snake = []; let food = null; let direction = { x: 1, y: 0 }; let queue = []; let score = 0; let best = Number(localStorage.getItem(storageKey)) || 0; let status = "ready"; let lastFrame = 0; let accumulator = 0; let animationFrame = 0; let touchStart = null;
    const overlay = document.getElementById("snakeOverlay"); const overlayTitle = document.getElementById("snakeOverlayTitle"); const overlayText = document.getElementById("snakeOverlayText"); const pauseButton = document.getElementById("snakePause");
    const directions = { up: { x: 0, y: -1 }, down: { x: 0, y: 1 }, left: { x: -1, y: 0 }, right: { x: 1, y: 0 } };
    function draw() { const cell = canvas.width / size; context.fillStyle = "#171a2b"; context.fillRect(0, 0, canvas.width, canvas.height); context.strokeStyle = "rgba(255,255,255,.045)"; context.lineWidth = 1; for (let index = 1; index < size; index += 1) { context.beginPath(); context.moveTo(index * cell, 0); context.lineTo(index * cell, canvas.height); context.stroke(); context.beginPath(); context.moveTo(0, index * cell); context.lineTo(canvas.width, index * cell); context.stroke(); } if (food) { context.fillStyle = "#f2b84b"; context.beginPath(); context.arc(food.x * cell + cell / 2, food.y * cell + cell / 2, cell * .33, 0, Math.PI * 2); context.fill(); } snake.forEach((part, index) => { context.fillStyle = index === 0 ? "#84e6a9" : "#35b978"; const inset = index === 0 ? 2 : 3; context.beginPath(); context.roundRect(part.x * cell + inset, part.y * cell + inset, cell - inset * 2, cell - inset * 2, 4); context.fill(); }); }
    function updateToolbar() { document.getElementById("snakeScore").textContent = score; document.getElementById("snakeBest").textContent = best; const multiplier = Math.min(2, 1 + Math.floor(score / 5) * .1); document.getElementById("snakeSpeed").textContent = `${multiplier.toFixed(1)}×`; }
    function spawnFood() { const free = []; for (let y = 0; y < size; y += 1) for (let x = 0; x < size; x += 1) if (!snake.some(part => part.x === x && part.y === y)) free.push({ x, y }); food = free.length ? free[Math.floor(Math.random() * free.length)] : null; }
    function speedInterval() { return Math.max(78, 155 - Math.floor(score / 5) * 8); }
    function isOpposite(next, current) { return next.x === -current.x && next.y === -current.y; }
    function setDirection(name) { const next = directions[name]; if (!next || status === "gameover") return; const reference = queue.length ? queue[queue.length - 1] : direction; if (isOpposite(next, reference) || (next.x === reference.x && next.y === reference.y)) return; if (queue.length < 3) queue.push(next); if (status === "ready") startGame(); }
    function tick() { if (queue.length) direction = queue.shift(); const head = { x: snake[0].x + direction.x, y: snake[0].y + direction.y }; if (head.x < 0 || head.x >= size || head.y < 0 || head.y >= size || snake.some(part => part.x === head.x && part.y === head.y)) return endGame(); snake.unshift(head); if (food && head.x === food.x && head.y === food.y) { score += 1; if (score > best) { best = score; localStorage.setItem(storageKey, String(best)); } spawnFood(); updateToolbar(); } else snake.pop(); draw(); }
    function loop(timestamp) { if (status === "running") { if (!lastFrame) lastFrame = timestamp; accumulator += timestamp - lastFrame; lastFrame = timestamp; while (accumulator >= speedInterval()) { tick(); accumulator -= speedInterval(); if (status !== "running") break; } } else lastFrame = timestamp; animationFrame = requestAnimationFrame(loop); }
    function showOverlay(title, text, buttonText) { overlayTitle.textContent = title; overlayText.textContent = text; document.getElementById("snakeStart").textContent = buttonText; overlay.classList.remove("hidden"); }
    function startGame() { if (status === "running") return; if (status === "gameover" || status === "paused") { if (status === "gameover") resetState(); else { status = "running"; overlay.classList.add("hidden"); pauseButton.textContent = "Pausa"; } return; } status = "running"; overlay.classList.add("hidden"); pauseButton.textContent = "Pausa"; }
    function resetState() { snake = [{ x: 10, y: 10 }, { x: 9, y: 10 }, { x: 8, y: 10 }]; direction = { x: 1, y: 0 }; queue = []; score = 0; status = "ready"; accumulator = 0; lastFrame = 0; spawnFood(); updateToolbar(); draw(); pauseButton.textContent = "Pausa"; showOverlay("Pronto?", "Usa le frecce, WASD o fai swipe per iniziare.", "Inizia"); }
    function endGame() { status = "gameover"; showOverlay("Game over", `Punteggio ${score}. Tenta di nuovo e supera il record.`, "Rigioca"); pauseButton.textContent = "Pausa"; }
    function togglePause() { if (status === "running") { status = "paused"; showOverlay("In pausa", "La partita è ferma. Riprendi quando vuoi.", "Riprendi"); pauseButton.textContent = "Riprendi"; } else if (status === "paused") startGame(); }
    document.addEventListener("keydown", event => { const map = { ArrowUp: "up", w: "up", W: "up", ArrowDown: "down", s: "down", S: "down", ArrowLeft: "left", a: "left", A: "left", ArrowRight: "right", d: "right", D: "right" }; if (map[event.key]) { event.preventDefault(); setDirection(map[event.key]); } else if (event.key === "p" || event.key === "P") { event.preventDefault(); togglePause(); } });
    document.querySelectorAll("[data-direction]").forEach(button => button.addEventListener("click", () => setDirection(button.dataset.direction)));
    canvas.addEventListener("touchstart", event => { const touch = event.changedTouches[0]; touchStart = { x: touch.clientX, y: touch.clientY }; }, { passive: true });
    canvas.addEventListener("touchend", event => { if (!touchStart) return; const touch = event.changedTouches[0]; const dx = touch.clientX - touchStart.x; const dy = touch.clientY - touchStart.y; touchStart = null; if (Math.max(Math.abs(dx), Math.abs(dy)) < 18) return; setDirection(Math.abs(dx) > Math.abs(dy) ? (dx > 0 ? "right" : "left") : (dy > 0 ? "down" : "up")); }, { passive: true });
    document.addEventListener("visibilitychange", () => { if (document.hidden && status === "running") togglePause(); }); window.addEventListener("blur", () => { if (status === "running") togglePause(); });
    document.getElementById("snakeStart").addEventListener("click", startGame); pauseButton.addEventListener("click", togglePause); document.getElementById("snakeNew").addEventListener("click", resetState); resetState(); updateToolbar(); animationFrame = requestAnimationFrame(loop);
    window.addEventListener("pagehide", () => cancelAnimationFrame(animationFrame), { once: true });
})();
