"use strict";
(function initWaterSort() {
    const tubesElement = document.getElementById("waterTubes"); if (!tubesElement) return;
    const capacity = 4; const storageKey = "cuginiparty_water_sort_progress_v1";
    const colors = { coral: "#ed6966", sky: "#4b9eea", mint: "#43c794", sun: "#f1bc45", violet: "#9a70db" };
    const levels = [
        { name: "1", tubes: [["coral","sky","mint","coral"],["mint","coral","sky","mint"],["sky","mint","coral","sky"],[],[]] },
        { name: "2", tubes: [["coral","sky","mint","sun"],["sun","mint","sky","coral"],["coral","sun","mint","sky"],["sky","coral","sun","mint"],[],[]] },
        { name: "3", tubes: [["coral","sky","mint","sun"],["violet","sun","mint","sky"],["coral","violet","sun","mint"],["sky","coral","violet","sun"],["mint","sky","coral","violet"],[],[]] }
    ];
    let currentLevel = 0; let tubes = []; let moves = 0; let selected = -1; let history = []; let bests = {}; let won = false;
    function clone(value) { return value.map(tube => tube.slice()); } function readSave() { try { return { ...JSON.parse(localStorage.getItem(storageKey) || "{}") }; } catch { return {}; } } function save() { localStorage.setItem(storageKey, JSON.stringify({ currentLevel, bests })); }
    function topGroupCount(tube) { if (!tube.length) return 0; let amount = 1; while (amount < tube.length && tube[tube.length - amount - 1] === tube[tube.length - 1]) amount += 1; return amount; }
    function canPour(from, to) { if (from === to || !tubes[from].length || tubes[to].length === capacity) return false; return !tubes[to].length || tubes[to][tubes[to].length - 1] === tubes[from][tubes[from].length - 1]; }
    function isComplete() { return tubes.every(tube => !tube.length || (tube.length === capacity && tube.every(color => color === tube[0]))); }
    function render() { tubesElement.innerHTML = ""; tubes.forEach((tube, tubeIndex) => { const button = document.createElement("button"); button.type = "button"; button.className = "water-tube"; if (tubeIndex === selected) button.classList.add("selected"); button.setAttribute("aria-label", tube.length ? `Provetta ${tubeIndex + 1}, ${tube.length} livelli d'acqua` : `Provetta ${tubeIndex + 1}, vuota`); tube.forEach((color, layer) => { const water = document.createElement("span"); water.className = "water-layer"; water.style.setProperty("--layer", String(layer)); water.style.setProperty("--water-color", colors[color]); button.appendChild(water); }); button.addEventListener("click", () => chooseTube(tubeIndex)); tubesElement.appendChild(button); }); document.getElementById("waterLevel").textContent = String(currentLevel + 1); document.getElementById("waterMoves").textContent = String(moves); document.getElementById("waterBest").textContent = bests[currentLevel] ? String(bests[currentLevel]) : "—"; document.getElementById("waterUndo").disabled = !history.length || won; document.getElementById("waterNext").hidden = !won; }
    function chooseTube(destination) { if (won) return; if (selected < 0) { if (tubes[destination].length) { selected = destination; document.getElementById("waterStatus").textContent = "Ora scegli dove versare."; render(); } return; } if (destination === selected) { selected = -1; document.getElementById("waterStatus").textContent = "Selezione annullata."; render(); return; } if (!canPour(selected, destination)) { document.getElementById("waterStatus").textContent = "Questa mossa non è possibile: scegli una provetta vuota o con lo stesso colore in cima."; return; } history.push({ tubes: clone(tubes), moves }); const count = Math.min(topGroupCount(tubes[selected]), capacity - tubes[destination].length); const moved = tubes[selected].splice(-count); tubes[destination].push(...moved); moves += 1; selected = -1; if (isComplete()) { won = true; if (!bests[currentLevel] || moves < bests[currentLevel]) bests[currentLevel] = moves; save(); document.getElementById("waterStatus").textContent = `Perfetto! Livello completato in ${moves} mosse.`; } else document.getElementById("waterStatus").textContent = "Bella mossa. Continua a separare i colori."; render(); }
    function resetLevel() { tubes = clone(levels[currentLevel].tubes); moves = 0; selected = -1; history = []; won = false; document.getElementById("waterStatus").textContent = "Livello ricominciato: scegli una provetta da cui versare."; render(); }
    function loadLevel(index) { currentLevel = (index + levels.length) % levels.length; save(); resetLevel(); }
    function undo() { const previous = history.pop(); if (!previous || won) return; tubes = clone(previous.tubes); moves = previous.moves; selected = -1; document.getElementById("waterStatus").textContent = "Mossa annullata."; render(); }
    const saved = readSave(); currentLevel = Number.isInteger(saved.currentLevel) && saved.currentLevel < levels.length ? saved.currentLevel : 0; bests = saved.bests && typeof saved.bests === "object" ? saved.bests : {};
    document.getElementById("waterUndo").addEventListener("click", undo); document.getElementById("waterRestart").addEventListener("click", resetLevel); document.getElementById("waterNext").addEventListener("click", () => loadLevel(currentLevel + 1)); loadLevel(currentLevel);
})();
